### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by DrBellubins** [VV-R/MC-Texture-Pack-Converter#1]
I'm trying to convert the Bare Bones resource pack (linked [here](https://modrinth.com/resourcepack/bare-bones)) and I cannot get this to work. I have unzipped it into a folder and created a folder for the converted pack, but I keep getting this error. I also installed pillow 10.2.0

Full error:
![WindowsTerminal_z7wP6fkdsI](https://github.com/VV-R/MC-Texture-Pack-Converter/assets/88703839/680651ee-17dc-4c48-be93-2ae2db16bc64)

Any help would be appreciated,
DrBellubins.

**Comment by VV-R** [comment]
Hi, your version of python is too old. You should be using 3.9 or newer to prevent this error.
Personally I have tested it with python 3.11.*.

**Comment by DrBellubins** [comment]
Thank you for your reply. This resolved my original issue, however I'm now getting a FileNotFound error: 
![WindowsTerminal_2xhTXZgJhi](https://github.com/VV-R/MC-Texture-Pack-Converter/assets/88703839/1e0adae3-b018-41e2-9a3c-b7d974ef595c)

In Bare Bones given with the link in my original post, there is no 'plants' directory in the 'textures/block' folder.

Apologies for the inconvenience.
Thanks for the help,
DrBellubins.

**Comment by VV-R** [comment]
Hi, no need to apologize and thank you for the feedback.

It seems that the resource pack you are trying to convert does not contain all the texture files.
I have added a feature that allows you to make the program skip missing textures.
Just add the -s or --skip-missing flag when executing the program.

There is one caveat though. Because it may skip some textures, the missing ones may become invisible (this will definitely happen to blocks). I will add a feature in the future which will make the program able to use the original textures from the game files if they are not available in the resource pack.

**Comment by DrBellubins** [comment]
This worked! Be advised, though, it seems to look for files with an extra .png extension:
![WindowsTerminal_PgDjnu6jfI](https://github.com/VV-R/MC-Texture-Pack-Converter/assets/88703839/07a73f51-81a6-4489-9416-112272400c10)

Thanks for the help, I'll go ahead and close this issue.

**Comment by VV-R** [comment]
Hi, thanks again for the feedback.
That was a formatting error and a wrongly typed out message format, but I fixed it.
